name: pre-commit

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: pre-commit/action@v2.0.3
