name: Automatic release

on:
  push:
    branches:
      - main

jobs:
  build-release:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/release-with-docker.yml@main
    with:
      image_name: geokrety/website-base
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
